name: blog_club
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/icons/
    - assets/img/posts/large/
    - assets/img/posts/small/
    - assets/img/stories/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTProBook.otf
          weight: 200
        - asset: assets/fonts/AvenirLTProRoman.otf
          weight: 300
        - asset: assets/fonts/AvenirLTProMedium.otf
          weight: 400
        - asset: assets/fonts/AvenirLTProHeavy.otf
          weight: 700